# -*- coding: utf-8 -*-
from pathlib import Path
import json,collections
B=Path(__file__).resolve().parents[1];O=B/'intermediate/mcode';R=B/'raw/mcode'
ms=[json.loads(l) for l in (O/'messages.jsonl').open()];ss={x['session_id']:x for x in map(json.loads,(O/'sessions.jsonl').open())};rows={x['line']:x for x in ms if x['profile']=='.minimax' and '#local_runtime_message_rows' in x['source_path']}
cases=[
('sandbox 层次边界被反复重新解释','mvs_a7d6c18b259a452e85f5e2e43539b6e0',[3801,4483,4497,4854],['沙箱只负责 bash 的拦截与否','我现在就希望, permission, sandbox, execute 三层分开','在开发期间, 都是用 feature 的 idl 去 generate的','第四轮修复已提交推送，CI 正在跑'], '用户在确定职责与产品语义，属于高价值决策；同一边界在实现后反复重申，则是契约没有约束实现的成本。IDL feature 分支协作规则也被 agent 误当问题，需要用户纠正。后续可见 depcruise 修复与提交声明，不能据此判定整条任务最终合入。', '把 permission 判定、sandbox 放行、execute 可恢复删除写成少量可执行契约测试；先跑原功能保真案例。已决定的 feature IDL 顺序用同一来源引用，避免每个 reviewer 重新裁决。'),
('四档权限之外增加保护','mvs_3d431041062b4c44aedde68b990055d5',[4951,4969,6802,7093],['我预设的等级是','我就希望按照这个来, 其他不符合的去掉','基于 architect 表格的 4个限制, 不要在加额外的保护','已按你的决定在两个仓库都移除了'], '用户首先发现 full access 与预期不符，然后授权去掉表格以外的行为。后续报告称删除 unused mandatoryDenyWrite，保留产品依赖的 unlinkAllowOnly；还承认自己引入敏感词 gate 失败并修复。这里存在明确的产品契约偏离及修复回路。', '从四档矩阵生成正反例，真实 shell 对读/写/删除逐项跑；把“未声明的保护也改变产品行为”加入 spec 验收，减少新增抽象后再拆除。'),
('sandbox 拆分与调度产生用户协调负担','mvs_e63208d747624f249704be7af9ba3d37',[23561,23645,24422,24682,27516,30020],['我现在觉得特别繁琐，实现起来特别慢','tickets 需要这么多吗? 不能合并','wp6 不对吧, 这都读一小时了','不是要复用吗? 为什么还要改','为什么不能多派点, 只要不依赖, 不能都派出去吗','开发完成之后就进行合并 然后交付完整的 MR'], '同一 session 里同时出现“任务太细”“独立任务为什么不并行”“复用为何变重写”。这不是简单要求更多或更少 agent，而是分解没有对应到用户期望的完整交付和依赖。用户暂停某个 WP、保留其他任务继续，也显示其承担了运行时调度。实际结束转向 Windows 真机验证条件，不据此认定两个 MR 已完成。', '按能独立验证的产品行为切片，先给单一 integrator 一个纵向运行路径；仅对可独立产出证据的分支并行，自动释放 ready-set，并把已有决策传给 worker。'),
('多 MR 汇总与固定头交叉审查','mvs_c04f334a2fbb4b328d994c86f0bd1c6b',[17208,18802,19314,19807],['把三个已创建 MR 整合为一个 MR','preserve all M6 code and tests','保持 Opus 5 xhigh，禁止派生或调用其他 agent/reviewer','真实 QueueRepository + 真实 priorityFence'], '这是已在使用的强流程：唯一整合者、保护其他 worker 已交付代码、独立审查后针对原 MR 修复。最终报告明确新 head 尚未交叉审查、checker 从未启动，保留验证边界。审查抓到了 selection 层让行未穿过真实 admit transaction 的缺口，说明模块自测不足以覆盖装配。', '保留独立审查，但让最便宜的真实 Queue→priorityFence→admit 测试先成为 worker 完成条件；每次只复查受改动影响的事实，避免固定头失效后重新整轮分析。'),
('短暂 provider 故障后的同会话恢复','mvs_4f8094b2e63a41f096d8c10bb37226a5',[14209,15077],['Continue the original task in this same session','TUI tarball 端到端产物验证 PASS'], '调度续跑明确要求先检查已有会话、worktree 和后台任务，保留进度。后续报告给出 !6680 与受影响单测/打包产物证据，并明确未跑 Electron 安装包链。该例体现恢复能力已存在；不能把所有续跑都算返工。', '复用同一 endpoint、提交和已有检查结果。把恢复后是否重复安装/搜索/测试作为专项指标；只在固定头发生变化或证据缺失时补跑。'),
('E2E 的入口和覆盖纠偏','mvs_d4af9fb602c14d2997f103f175f69717',[20668,21233,21624],['只通过 TUI（真实终端 PTY）','不把文本 PASS 当作附件 PASS','G04 整体降为 **PARTIAL**'], '原验收被调度纠正为真实 TUI 入口；第二轮纠正附件覆盖、stale 计费/恢复路径和事件顺序推断。结果退回 PARTIAL/NOT_RUN，并撤回 token 近乎翻倍与微观时序结论。说明独立核验有价值，也说明最初验收矩阵未强制绑定产品入口与证据。', '为每个验收项绑定入口、预期可观察量、源记录和允许的状态（PASS/PARTIAL/NOT_RUN）。runner 在入口错误或缺失证据时不能输出 PASS；依赖真实 provider 的测试与确定性集成测试分开。'),
('安装排障扩大任务范围','mvs_ed3fb5789c7449899cde012d690472cd',[21448,21678,21892,21916],['正常终止但没有任何有效输出时静默结束','安装排障已越界且耗时过多','不要再 sleep 或轮询等未来状态','已完成并收尾'], '实际修复目标是空响应重试，期间扩展到共享 pnpm store 索引与编辑器目录权限探针，调度 SIGINT 后要求恢复 7 个缓存索引，再以现有 CI 验证交付。后续报告提供 !6832/SHA，明确 CI 与未做真实上游回放边界。SIGINT 是主动纠偏，不能计成模型故障。', '给环境恢复设行为边界：复用已可用依赖与现有 CI，依赖修复触及共享目录时回到任务检查点。以“能否验证本次改动”决定下一步，避免把修工具环境变成隐含子项目。'),
('嵌套 runtime 修复先膨胀再缩小','mvs_f6523fb596974197931841d92a3e414f',[52165,52509,52912,53066,53096],['不得只缩短锁超时','Continue the original task in this same session','without reimplementing the fix','当前改动（35 files，约 +3291/-49）过多','bridge 那 1061 行协议机器'], '恢复与交付机制表现良好；架构成本却在实现后才被审视。当前报告提出约700–750行的 guard 方案，相比3291行 bridge，并指出常见嵌套 exec 仍 fail fast。这里的规模与方案是当时 agent 审核结论，本次未重读现仓确认后续实施结果。', '实现前列出“复用已有能力/加一个 guard/新增协议”三种成本，先做最小实验验证需要哪个。对跨进程协议、新生命周期所有权这类复杂度明确要求一个已证实的用户场景。'),
('owned_paths 与必要架构测试形成边界冲突','mvs_13120517afbb4af4bb588ddda243dad0',[71527,72631,72673],['Do not merge or cherry-pick dependency branches','two changed paths outside the module','owned-path-only 等价实现不存在'], 'worker 在冻结基线上实现 assembly，交付后因两个越界路径返工。一处是目标分支已有的 stub，另一处是新增门面导出必须同步的精确测试白名单。后续报告移除 stub 后 package typecheck 因旧基线 abstract 成员失败，lr2 自身检查通过。该例说明静态路径边界和实际依赖/验证需要不一致。', 'planner 在分派前把架构验收文件纳入真实所有权，并验证基线可编译；下游进入执行时用依赖交付后的整合基线。尽量通过包接口/验收边界分工，避免要求 worker 既改公开导出又不能改其契约测试。'),
('Goal v2 模块完成没有保证默认生产装配启用','mvs_973ac1224db74f25a177d275465ed8cc',[72967,73666,74288,75479],['single final integrator','Diagnose the complete job traces','production Goal composition gap is not a new scope item','Environment banner is stale'], '调度明确指出默认 Goal capability 仍 disabled，是原 assembly 义务未交付，要求真实 production adapter 与生命周期接线。之后仍在探索接口，最后可见工具 cd packages/goal 报 No such file or directory。此 MCode session 内没有最终交付，但跨端关联已发现 Claude session `2d2b5c29-72bd-4513-bdd7-cff795e5f5ad` 于 2026-09-23 07:09Z 明示接续并随后给出交付声明（见 `../claude/analysis.md` C13，原 `/Users/minimax/.claude/projects/-Users-minimax--codex-state-agent-lord-worktrees-goal-v2-feat-mr-mcode-20260921/2d2b5c29-72bd-4513-bdd7-cff795e5f5ad.jsonl` L17/L93 接续，L5216 交付声明；本地失败与CI结果须分开）。因此这里只能说单端没有终局，不能说任务未完成；也不能把工具目录错误推导为全部架构根因。', '在大并行改造开始前建立最薄默认生产链路测试，明确无注入运行时 Goal 必须可用；之后模块迁移持续保持这一条红绿信号。integrator 早运行，持续检查默认 composition，而非最后把模块相加。'),
('六模块跨仓整合与 CI 等待','mvs_68c510859bf74d39ac455693c55c415a',[47288,48133,48219,48226],['worker 全绿不等于可以合入','do a final CI check','newly failed after a docs-only merge','never reached typecheck'], '整合任务明确给两个 worktree、唯一整合责任、6模块来源，属于合理分工。最后可见 CI 失败发生 pnpm install、未到 typecheck，agent 决定重试；本记录没有最终报告。不能把这次基础设施问题当代码测试失败。文档合并后的 CI 追踪也提示验证触发需按实际 diff，而当前全局已有 docs-only 不追CI规则。', '保存 checks→SHA→影响路径的映射，复用有效结果；依赖安装失败按基础设施单列，避免重启整条验证；让当前 docs-only 规则由执行入口识别，不依赖长提示词中途提醒。'),
('视频迭代需要真正的视觉闭环','mvs_a08618b5e6e94310aa0e8f43503d051f',[62955,63221,63804,63976,64486,64498],['排名超过 GLM 5.3 max','插入速度有点快','我图片这个是水平排列, 你为什么是垂直排列','模型保留颜色','模型无图像视觉能力','视频已渲染完成并通过成片验证'], '用户先后纠正速度、横竖布局、后半空白、模型色和移动路径。agent 最后用 ffprobe+像素聚类验证几何，仍明确模型无图像视觉能力。几何信号有价值，但不足以证明视觉语义或审美；这是可借 Lauren 操作真实产品并看到结果的直接案例。', '选有图像输入的验证 agent，在布局原型、运动中帧、最终帧与成片四个点核对原参考；把方向、颜色、最终排序先变成短验收表，避免渲染后由用户承担全部视觉判断。'),
('已经把重复问题变成工具和 CI','mvs_20a4a71feb5945f990e3c38388d0f875',[65167,65207,66193],['skill 的目前描述是不是太多了','整体扫描下列出优化项','schemas round-trip 测试'], '后续报告称修复 schema 漂移、拆分协议文档、加 docs 链接与 skill体积门禁，交付 PR34；335/336 的测试结果没有被写成全绿，说明边界意识已较成熟。这里与 Lauren 把重复错误转成可执行约束一致，不需要再加一层通用流程。', '优先继续这条路线：当同类协调错误重复发生，改已有工具的返回结构/自动检查；定期删除已由代码保证的提示词。选择能阻止真实已发生错误的 gate。')]
out=['# MCode 最近30天工作流证据分析','','窗口：2026-08-25 09:33:02 UTC ≤ event timestamp < 2026-09-24 09:33:02 UTC。','', '## 3 个优先结论','', '1. 用户最稀缺的注意力集中在产品边界、复用和验收语义；重复解释已定边界、询问任务状态、收紧入口的工作应迁到可执行契约与调度事实。','2. 并行规模已经很高。最明显的收益点是让 integrator 提前跑最薄生产链路，并使依赖交付后的真实基线进入下游，降低末端补接线与边界返工。','3. 恢复、固定 SHA、独立复核与诚实的 PARTIAL 报告已经是优势。应延续这些能力，将重复的人肉检查固化到现有工具、真实产品探针与 CI，而不是再增加通用审批层。','', '## 覆盖与口径','', '全量机器扫描65个可发现 `.minimax*` profile的已知runtime目录、SQLite及旧版SQLite；16个profile在窗口有可见消息。归并得到758会话、38,995条可见消息，其中主profile644会话/38,478消息，开发profile114会话/517消息。主profile43,535次tool-call条目，不等于独立命令或实际有效动作。','', '主profile分为显式Agent Lord委派148、native child257、推断委派6、交互或未分类233。569条主profile根输入并未逐条证明为真人输入，不估算真人占比。父子及Agent Lord关系见sessions.jsonl。下述13条任务链共5,759条窗口可见消息；阅读方式是完整提取链条，重点核对用户要求、纠正、阶段交接、最后可见结果及关联工具证据，未逐字人工听读所有工具输出。','', '不提供session成功率或以首末timestamp估计工作时长。缺少结尾可能来自中断、截窗、迁移、另一个端点交付；current_status是采集时元数据，不代表历史结果。以下“后续报告称”均指session内可见声明，本次未实时回读历史MR。','']
structured=[]
for i,(title,sid,ns,quotes,finding,action) in enumerate(cases,1):
 s=ss[sid];out.extend([f'## C{i:02d} {title}','',f'会话：`{sid}`；分类：{s["session_class"]}；窗口消息：{s["messages"]}；[完整可见文本摘录](case-evidence/{sid}.md)。',''])
 evid=[]
 for n,q in zip(ns,quotes):
  r=rows[n];present=q in r['text'];quote=q if present else r['text'][:180]
  out.extend([f'- {r["timestamp"]}，{r["role"]}，SQLite `local_runtime_message_rows.id={n}`：','',f'  > {quote}','',f'  来源：`{r["source_path"]}`；规范化`messages.jsonl`字段`line={n}`。',''])
  evid.append({'source_path':r['source_path'],'line':n,'timestamp':r['timestamp'],'role':r['role'],'quote':quote})
 out.extend(['**观察与后续边界：** '+finding,'','**可以改进：** '+action,''])
 structured.append({'case_id':f'C{i:02d}','title':title,'session_id':sid,'evidence':evid,'finding':finding,'recommendation':action})
(O/'analysis.md').write_text('\n'.join(out));(O/'cases.json').write_text(json.dumps(structured,ensure_ascii=False,indent=2)+'\n')
